INSERT INTO Exercises (Title, Category) VALUES('Alternate Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Alternate-Leg Bounding', 1);
INSERT INTO Exercises (Title, Category) VALUES('Arnold Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Back Extension', 2);
INSERT INTO Exercises (Title, Category) VALUES('Basic Burpee', 1);
INSERT INTO Exercises (Title, Category) VALUES('Bench Dips', 2);
INSERT INTO Exercises (Title, Category) VALUES('Bench Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Bent-over Row', 2);
INSERT INTO Exercises (Title, Category) VALUES('Biceps Curl', 2);
INSERT INTO Exercises (Title, Category) VALUES('Bicycle', 1);
INSERT INTO Exercises (Title, Category) VALUES('Box Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Butt Kick', 1);
INSERT INTO Exercises (Title, Category) VALUES('Cable Crossovers', 2);
INSERT INTO Exercises (Title, Category) VALUES('Cable Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Cable Extensions', 2);
INSERT INTO Exercises (Title, Category) VALUES('Cable Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Cable Press-Downs', 2);
INSERT INTO Exercises (Title, Category) VALUES('Cable Pull-Throughs', 2);
INSERT INTO Exercises (Title, Category) VALUES('Chest Fly', 2);
INSERT INTO Exercises (Title, Category) VALUES('Chest Supported Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Chin-Ups', 2);
INSERT INTO Exercises (Title, Category) VALUES('Close Grip Push-Ups', 2);
INSERT INTO Exercises (Title, Category) VALUES('Concentration Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Deadlift', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Bench Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Chest Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Close Grip Bench Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Decline Oblique', 2);
INSERT INTO Exercises (Title, Category) VALUES('Dips', 2);
INSERT INTO Exercises (Title, Category) VALUES('Driver''s Push-up', 1);
INSERT INTO Exercises (Title, Category) VALUES('Dumbbell, Cable or Machine Front Raises', 2);
INSERT INTO Exercises (Title, Category) VALUES('Elliptical', 1);
INSERT INTO Exercises (Title, Category) VALUES('Flat Chest Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Flat Close Grip Bench Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Flat Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Floor Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Flutter Kick', 1);
INSERT INTO Exercises (Title, Category) VALUES('Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Foot Fire', 1);
INSERT INTO Exercises (Title, Category) VALUES('Frog Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Front Raises', 2);
INSERT INTO Exercises (Title, Category) VALUES('Front Squats', 2);
INSERT INTO Exercises (Title, Category) VALUES('Glute-Ham Raises', 2);
INSERT INTO Exercises (Title, Category) VALUES('Good-Mornings', 2);
INSERT INTO Exercises (Title, Category) VALUES('Hack Squat', 2);
INSERT INTO Exercises (Title, Category) VALUES('Hammer Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Hanging Knee Raises', 2);
INSERT INTO Exercises (Title, Category) VALUES('High Knees', 1);
INSERT INTO Exercises (Title, Category) VALUES('Hip Abductor', 2);
INSERT INTO Exercises (Title, Category) VALUES('Hyperextensions ', 2);
INSERT INTO Exercises (Title, Category) VALUES('Inchworm', 1);
INSERT INTO Exercises (Title, Category) VALUES('Incline Bench Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Incline Chest Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Incline Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Incline Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Incline Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Inverted Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Invisible Jump Rope', 1);
INSERT INTO Exercises (Title, Category) VALUES('Jumping Jack', 1);
INSERT INTO Exercises (Title, Category) VALUES('Jumping Jack Planks', 1);
INSERT INTO Exercises (Title, Category) VALUES('Lat Pull-Downs', 2);
INSERT INTO Exercises (Title, Category) VALUES('Lateral Raise', 2);
INSERT INTO Exercises (Title, Category) VALUES('Lateral Stepover', 1);
INSERT INTO Exercises (Title, Category) VALUES('Laying Triceps Extensions', 2);
INSERT INTO Exercises (Title, Category) VALUES('Leg Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Leg Extension', 2);
INSERT INTO Exercises (Title, Category) VALUES('Leg Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Leg Raise', 2);
INSERT INTO Exercises (Title, Category) VALUES('Long Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Lunge', 2);
INSERT INTO Exercises (Title, Category) VALUES('Lunge Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Lying Leg Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Lying Triceps Presses', 2);
INSERT INTO Exercises (Title, Category) VALUES('Mountain Climber', 1);
INSERT INTO Exercises (Title, Category) VALUES('Oblique Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Oblique Floor Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('One-Arms Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Overhead Machine Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Overhead Triceps Extensions', 2);
INSERT INTO Exercises (Title, Category) VALUES('Pec Deck', 2);
INSERT INTO Exercises (Title, Category) VALUES('Plank to Push-up', 1);
INSERT INTO Exercises (Title, Category) VALUES('Polyometric Push-up', 1);
INSERT INTO Exercises (Title, Category) VALUES('Power Punch', 1);
INSERT INTO Exercises (Title, Category) VALUES('Power Skip', 1);
INSERT INTO Exercises (Title, Category) VALUES('Preacher Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Pull-Ups', 2);
INSERT INTO Exercises (Title, Category) VALUES('Pulldown', 2);
INSERT INTO Exercises (Title, Category) VALUES('Pushdown', 2);
INSERT INTO Exercises (Title, Category) VALUES('Rear Delt Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Reverse Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Reverse Flyes', 2);
INSERT INTO Exercises (Title, Category) VALUES('Romanian Deadlifts', 2);
INSERT INTO Exercises (Title, Category) VALUES('Rowing', 1);
INSERT INTO Exercises (Title, Category) VALUES('Russian Twist', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Cable Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Calf Raise', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Overhead Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Seated Triceps Presses', 2);
INSERT INTO Exercises (Title, Category) VALUES('Shoulder Fly', 2);
INSERT INTO Exercises (Title, Category) VALUES('Shoulder Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Shoulder Shrug', 2);
INSERT INTO Exercises (Title, Category) VALUES('Single-Leg Box Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Single-Leg Burpee', 1);
INSERT INTO Exercises (Title, Category) VALUES('Single-Leg Hop', 1);
INSERT INTO Exercises (Title, Category) VALUES('Skater''s Lunge', 1);
INSERT INTO Exercises (Title, Category) VALUES('Skull Crunches', 2);
INSERT INTO Exercises (Title, Category) VALUES('Split Squats', 2);
INSERT INTO Exercises (Title, Category) VALUES('Sprinter Sit-up', 1);
INSERT INTO Exercises (Title, Category) VALUES('Squat', 2);
INSERT INTO Exercises (Title, Category) VALUES('Squat Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Stair Climb', 1);
INSERT INTO Exercises (Title, Category) VALUES('Standing Calf Raise', 2);
INSERT INTO Exercises (Title, Category) VALUES('Standing Curls', 2);
INSERT INTO Exercises (Title, Category) VALUES('Standing Heel Raises', 2);
INSERT INTO Exercises (Title, Category) VALUES('Standing Overhead Press', 2);
INSERT INTO Exercises (Title, Category) VALUES('Stationary Bike', 1);
INSERT INTO Exercises (Title, Category) VALUES('Step-Ups', 2);
INSERT INTO Exercises (Title, Category) VALUES('Straight Arm Pulldowns', 2);
INSERT INTO Exercises (Title, Category) VALUES('Straight Leg Deadlifts', 2);
INSERT INTO Exercises (Title, Category) VALUES('Sumo Deadlifts', 2);
INSERT INTO Exercises (Title, Category) VALUES('T-Bar Rows', 2);
INSERT INTO Exercises (Title, Category) VALUES('Tabata Crunch', 1);
INSERT INTO Exercises (Title, Category) VALUES('Tradmill', 1);
INSERT INTO Exercises (Title, Category) VALUES('Triceps Extensions', 2);
INSERT INTO Exercises (Title, Category) VALUES('Triceps Kickbacks', 2);
INSERT INTO Exercises (Title, Category) VALUES('Triceps Pushdowns', 2);
INSERT INTO Exercises (Title, Category) VALUES('Tuck Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Uppercut', 1);
INSERT INTO Exercises (Title, Category) VALUES('Upright Row', 2);
INSERT INTO Exercises (Title, Category) VALUES('Vertical Jump', 1);
INSERT INTO Exercises (Title, Category) VALUES('Wide-Grip Lat Pulldowns', 2);